package com.xdao7.xdweather.logic.model

import com.xdao7.xdweather.R

class Sky(val smallIcon: Int, val bgDay: Int, val bgNight: Int)

private val sky = mapOf(
    100 to Sky(R.drawable.ic_weather_1,  R.drawable.bg_clear_day,        R.drawable.bg_clear_day,          ),
    101 to Sky(R.drawable.ic_weather_2,  R.drawable.bg_cloudy_day,       R.drawable.bg_cloudy_night,       ),
    102 to Sky(R.drawable.ic_weather_3,  R.drawable.bg_cloudy_day,       R.drawable.bg_cloudy_night,       ),
    103 to Sky(R.drawable.ic_weather_4,  R.drawable.bg_cloudy_day,       R.drawable.bg_cloudy_day,         ),
    104 to Sky(R.drawable.ic_weather_5,  R.drawable.bg_overcast_day,     R.drawable.bg_overcast_day,       ),
    150 to Sky(R.drawable.ic_weather_6,  R.drawable.bg_clear_night,      R.drawable.bg_clear_night,        ),
    153 to Sky(R.drawable.ic_weather_7,  R.drawable.bg_cloudy_night,     R.drawable.bg_cloudy_night,       ),
    154 to Sky(R.drawable.ic_weather_8,  R.drawable.bg_overcast_night,   R.drawable.bg_overcast_night,     ),
    300 to Sky(R.drawable.ic_weather_9,  R.drawable.bg_rain_day,         R.drawable.bg_rain_day,           ),
    301 to Sky(R.drawable.ic_weather_10, R.drawable.bg_rain_day,         R.drawable.bg_rain_day,           ),
    302 to Sky(R.drawable.ic_weather_11, R.drawable.bg_thunderstorm_day, R.drawable.bg_thunderstorm_night, ),
    303 to Sky(R.drawable.ic_weather_12, R.drawable.bg_thunderstorm_day, R.drawable.bg_thunderstorm_night, ),
    304 to Sky(R.drawable.ic_weather_13, R.drawable.bg_thunderstorm_day, R.drawable.bg_thunderstorm_night, ),
    305 to Sky(R.drawable.ic_weather_14, R.drawable.bg_rain_day,         R.drawable.bg_rain_night,         ),
    306 to Sky(R.drawable.ic_weather_15, R.drawable.bg_rain_day,         R.drawable.bg_rain_night,         ),
    307 to Sky(R.drawable.ic_weather_16, R.drawable.bg_rain_day,         R.drawable.bg_rain_night,         ),
    308 to Sky(R.drawable.ic_weather_17, R.drawable.bg_rain_day,         R.drawable.bg_rain_night,         ),
    309 to Sky(R.drawable.ic_weather_18, R.drawable.bg_rain_day,         R.drawable.bg_rain_night,         ),
    310 to Sky(R.drawable.ic_weather_19, R.drawable.bg_rain_day,         R.drawable.bg_rain_night,         ),
    311 to Sky(R.drawable.ic_weather_20, R.drawable.bg_rain_day,         R.drawable.bg_rain_night,         ),
    312 to Sky(R.drawable.ic_weather_21, R.drawable.bg_rain_day,         R.drawable.bg_rain_night,         ),
    313 to Sky(R.drawable.ic_weather_22, R.drawable.bg_rain_day,         R.drawable.bg_rain_night,         ),
    314 to Sky(R.drawable.ic_weather_23, R.drawable.bg_rain_day,         R.drawable.bg_rain_night,         ),
    315 to Sky(R.drawable.ic_weather_24, R.drawable.bg_rain_day,         R.drawable.bg_rain_night,         ),
    316 to Sky(R.drawable.ic_weather_25, R.drawable.bg_rain_day,         R.drawable.bg_rain_night,         ),
    317 to Sky(R.drawable.ic_weather_26, R.drawable.bg_rain_day,         R.drawable.bg_rain_night,         ),
    318 to Sky(R.drawable.ic_weather_27, R.drawable.bg_rain_day,         R.drawable.bg_rain_night,         ),
    399 to Sky(R.drawable.ic_weather_28, R.drawable.bg_rain_day,         R.drawable.bg_rain_night,         ),
    350 to Sky(R.drawable.ic_weather_29, R.drawable.bg_rain_night,       R.drawable.bg_rain_night,         ),
    351 to Sky(R.drawable.ic_weather_30, R.drawable.bg_rain_night,       R.drawable.bg_rain_night,         ),
    400 to Sky(R.drawable.ic_weather_31, R.drawable.bg_snow_day,         R.drawable.bg_snow_night,         ),
    401 to Sky(R.drawable.ic_weather_32, R.drawable.bg_snow_day,         R.drawable.bg_snow_night,         ),
    402 to Sky(R.drawable.ic_weather_33, R.drawable.bg_snow_day,         R.drawable.bg_snow_night,         ),
    403 to Sky(R.drawable.ic_weather_34, R.drawable.bg_snow_day,         R.drawable.bg_snow_night,         ),
    404 to Sky(R.drawable.ic_weather_35, R.drawable.bg_snow_day,         R.drawable.bg_snow_night,         ),
    405 to Sky(R.drawable.ic_weather_36, R.drawable.bg_snow_day,         R.drawable.bg_snow_night,         ),
    406 to Sky(R.drawable.ic_weather_37, R.drawable.bg_snow_day,         R.drawable.bg_snow_day,           ),
    407 to Sky(R.drawable.ic_weather_38, R.drawable.bg_snow_day,         R.drawable.bg_snow_day,           ),
    408 to Sky(R.drawable.ic_weather_39, R.drawable.bg_snow_day,         R.drawable.bg_snow_night,         ),
    409 to Sky(R.drawable.ic_weather_40, R.drawable.bg_snow_day,         R.drawable.bg_snow_night,         ),
    410 to Sky(R.drawable.ic_weather_41, R.drawable.bg_snow_day,         R.drawable.bg_snow_night,         ),
    499 to Sky(R.drawable.ic_weather_42, R.drawable.bg_snow_day,         R.drawable.bg_snow_night,         ),
    456 to Sky(R.drawable.ic_weather_43, R.drawable.bg_snow_night,       R.drawable.bg_snow_night,         ),
    457 to Sky(R.drawable.ic_weather_44, R.drawable.bg_snow_night,       R.drawable.bg_snow_night,         ),
    500 to Sky(R.drawable.ic_weather_45, R.drawable.bg_fog_day,          R.drawable.bg_fog_night,          ),
    501 to Sky(R.drawable.ic_weather_46, R.drawable.bg_fog_day,          R.drawable.bg_fog_night,          ),
    502 to Sky(R.drawable.ic_weather_47, R.drawable.bg_haze_day,         R.drawable.bg_haze_night,         ),
    503 to Sky(R.drawable.ic_weather_48, R.drawable.bg_dust_day,         R.drawable.bg_dust_night,         ),
    504 to Sky(R.drawable.ic_weather_49, R.drawable.bg_dust_day,         R.drawable.bg_dust_night,         ),
    507 to Sky(R.drawable.ic_weather_50, R.drawable.bg_dust_day,         R.drawable.bg_dust_night,         ),
    508 to Sky(R.drawable.ic_weather_51, R.drawable.bg_dust_day,         R.drawable.bg_dust_night,         ),
    509 to Sky(R.drawable.ic_weather_52, R.drawable.bg_fog_day,          R.drawable.bg_fog_night,          ),
    510 to Sky(R.drawable.ic_weather_53, R.drawable.bg_fog_day,          R.drawable.bg_fog_night,          ),
    511 to Sky(R.drawable.ic_weather_54, R.drawable.bg_fog_day,          R.drawable.bg_fog_night,          ),
    512 to Sky(R.drawable.ic_weather_55, R.drawable.bg_fog_day,          R.drawable.bg_fog_night,          ),
    513 to Sky(R.drawable.ic_weather_56, R.drawable.bg_fog_day,          R.drawable.bg_fog_night,          ),
    514 to Sky(R.drawable.ic_weather_57, R.drawable.bg_fog_day,          R.drawable.bg_fog_night,          ),
    515 to Sky(R.drawable.ic_weather_58, R.drawable.bg_fog_day,          R.drawable.bg_fog_night,          ),
    900 to Sky(R.drawable.ic_weather_59, R.drawable.bg_hot_day,          R.drawable.bg_hot_night,          ),
    901 to Sky(R.drawable.ic_weather_60, R.drawable.bg_cold_day,         R.drawable.bg_cold_night,         ),
    999 to Sky(R.drawable.ic_weather_61, R.drawable.bg_clear_day,        R.drawable.bg_clear_night,        )
)

fun getSky(code: Int): Sky {
    return sky[code] ?: sky[0]!!
}
